# Topic 10 — Combining DataFrames with Pandas — 📖 Lesson

## `concat()` · `merge()` · `join()` — from basics to professional use

> **Analogy:** Think of DataFrames as sheets of paper.
> - **`concat`** = **stacking** sheets on top of each other (more rows) or taping them side by side (more columns).
> - **`merge`** = **matching** two lists by a shared ID, like matching a customer list with an order list by customer number.
> - **`join`** = a shortcut for merge that matches on the **index** (row labels).

### Roadmap

| Part | Sections |
|---|---|
| 🟢 **Why & concat** | 1 Why combine · 2 `concat()` · 3 Row-wise · 4 Column-wise · 5 Different columns |
| 🟡 **merge** | 6 `merge()` · 7 Join types · 8 Visual explanation · 9 Different key names · 10 Multiple keys · 11 Suffixes · 12 Relationship types · 13 `validate` · 14 `indicator` |
| 🟡 **join & comparison** | 15 `join()` · 16 merge vs join vs concat |
| 🔴 **Safety & real world** | 17 Duplicate keys · 18 Preventing bad merges · 19 Three real tables · 20 Advanced (multi-merge, aggregation, MultiIndex, `merge_asof`, `merge_ordered`, many files) · 21 Common mistakes |
| 📝 **Practice** | 20 problems → Solutions |
| 🚀 **Project** | E-Commerce Database Integration |
| 📋 **Reference** | Cheat sheet |

Every major concept: **What · Why · When · When not · Syntax · Small example · Expected output · Explanation · Common mistakes**.

> 📚 **Course navigation** — you are in **Topic 10: Combining DataFrames**
> ⬅️ Previous: [Topic 09 — Pandas Data Manipulation](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb)  ·  ➡️ Next: [Topic 11 — Feature Engineering](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

<details><summary>Full course sequence (click to expand)</summary>

| # | Topic | Lesson | Practice & Solutions |
|---|---|---|---|
| 01 | Python Basics | [📖 Lesson](../Topic_01_Python_Basics/Topic_01_Lesson.ipynb) | [✍️ Practice](../Topic_01_Python_Basics/Topic_01_Practice_Solutions.ipynb) |
| 02 | Pandas DataFrame Basics | [📖 Lesson](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Lesson.ipynb) | [✍️ Practice](../Topic_02_Pandas_DataFrame_Basics/Topic_02_Practice_Solutions.ipynb) |
| 03 | Handling Missing Values | [📖 Lesson](../Topic_03_Handling_Missing_Values/Topic_03_Lesson.ipynb) | [✍️ Practice](../Topic_03_Handling_Missing_Values/Topic_03_Practice_Solutions.ipynb) |
| 04 | Normalization & Standardization | [📖 Lesson](../Topic_04_Normalization_Standardization/Topic_04_Lesson.ipynb) | [✍️ Practice](../Topic_04_Normalization_Standardization/Topic_04_Practice_Solutions.ipynb) |
| 05 | Detecting & Treating Outliers | [📖 Lesson](../Topic_05_Outliers/Topic_05_Lesson.ipynb) | [✍️ Practice](../Topic_05_Outliers/Topic_05_Practice_Solutions.ipynb) |
| 06 | Encoding Techniques | [📖 Lesson](../Topic_06_Encoding_Techniques/Topic_06_Lesson.ipynb) | [✍️ Practice](../Topic_06_Encoding_Techniques/Topic_06_Practice_Solutions.ipynb) |
| 07 | Exploratory Data Analysis (EDA) | [📖 Lesson](../Topic_07_Exploratory_Data_Analysis/Topic_07_Lesson.ipynb) | [✍️ Practice](../Topic_07_Exploratory_Data_Analysis/Topic_07_Practice_Solutions.ipynb) |
| 08 | Data Visualization | [📖 Lesson](../Topic_08_Data_Visualization/Topic_08_Lesson.ipynb) | [✍️ Practice](../Topic_08_Data_Visualization/Topic_08_Practice_Solutions.ipynb) |
| 09 | Pandas Data Manipulation | [📖 Lesson](../Topic_09_Pandas_Data_Manipulation/Topic_09_Lesson.ipynb) | [✍️ Practice](../Topic_09_Pandas_Data_Manipulation/Topic_09_Practice_Solutions.ipynb) |
| **▶ 10 ◀** | **Combining DataFrames** | [📖 Lesson](../Topic_10_Combining_DataFrames/Topic_10_Lesson.ipynb) | [✍️ Practice](../Topic_10_Combining_DataFrames/Topic_10_Practice_Solutions.ipynb) |
| 11 | Feature Engineering | [📖 Lesson](../Topic_11_Feature_Engineering/Topic_11_Lesson.ipynb) | [✍️ Practice](../Topic_11_Feature_Engineering/Topic_11_Practice_Solutions.ipynb) |
| 11b | KBinsDiscretizer (Discretization) | [📖 Lesson](../Topic_11b_KBinsDiscretizer/Topic_11b_Lesson.ipynb) | [✍️ Practice](../Topic_11b_KBinsDiscretizer/Topic_11b_Practice_Solutions.ipynb) |
| 12 | Correlation & Multicollinearity | [📖 Lesson](../Topic_12_Correlation_Multicollinearity/Topic_12_Lesson.ipynb) | [✍️ Practice](../Topic_12_Correlation_Multicollinearity/Topic_12_Practice_Solutions.ipynb) |
| 13 | Data Transformation & Skewness | [📖 Lesson](../Topic_13_Data_Transformation_Skewness/Topic_13_Lesson.ipynb) | [✍️ Practice](../Topic_13_Data_Transformation_Skewness/Topic_13_Practice_Solutions.ipynb) |
| 14 | Statistics for Data Science | [📖 Lesson](../Topic_14_Statistics_for_Data_Science/Topic_14_Lesson.ipynb) | [✍️ Practice](../Topic_14_Statistics_for_Data_Science/Topic_14_Practice_Solutions.ipynb) |
| 15 | Probability for Data Science & ML | [📖 Lesson](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Lesson.ipynb) | [✍️ Practice](../Topic_15_Probability_for_Data_Science_ML/Topic_15_Practice_Solutions.ipynb) |
| 16 | Feature Selection | [📖 Lesson](../Topic_16_Feature_Selection/Topic_16_Lesson.ipynb) | [✍️ Practice](../Topic_16_Feature_Selection/Topic_16_Practice_Solutions.ipynb) |
| 17 | Machine Learning | [📖 Lesson](../Topic_17_Machine_Learning/Topic_17_Lesson.ipynb) | [✍️ Practice](../Topic_17_Machine_Learning/Topic_17_Practice_Solutions.ipynb) |

</details>

## 📋 Lesson Index — What This Lesson Covers

This lesson has **31 sections**. Click any one to jump to it.

- [1. Why Do We Combine DataFrames?](#sec-1)
- [2. `pd.concat()`](#sec-2)
- [3. Row-wise Concatenation (monthly datasets)](#sec-3)
- [4. Column-wise Concatenation — `axis=1`](#sec-4)
- [5. `concat()` with Different Columns](#sec-5)
- [6. `pd.merge()` — joining tables on a key](#sec-6)
- [7. Types of Merge](#sec-7)
- [7.1 Inner join — `how='inner'`](#sec-8)
- [7.2 Left join — `how='left'`](#sec-9)
- [7.3 Right join — `how='right'`](#sec-10)
- [7.4 Outer join — `how='outer'`](#sec-11)
- [8. Visual Explanation of Joins](#sec-12)
- [9. Merge on Different Column Names — `left_on` / `right_on`](#sec-13)
- [10. Multiple Keys (composite keys)](#sec-14)
- [11. Merge with Suffixes](#sec-15)
- [12. Relationship Types: One-to-One, One-to-Many, Many-to-One, Many-to-Many](#sec-16)
- [13. Validate the Merge — `validate=`](#sec-17)
- [14. Merge Indicator — `indicator=True`](#sec-18)
- [15. `df.join()`](#sec-19)
- [16. `merge` vs `join` vs `concat`](#sec-20)
- [17. Handling Duplicate Keys](#sec-21)
- [18. Preventing Bad Merges — Checklist](#sec-22)
- [19. Combining Real-World Tables: Customers + Orders + Products](#sec-23)
- [20. Advanced Combining](#sec-24)
- [20.1 Merge multiple DataFrames](#sec-25)
- [20.2 Merge after aggregation](#sec-26)
- [20.3 Merge with indexes, 20.4 MultiIndex joins](#sec-27)
- [20.5 `pd.merge_asof()` — nearest-key (time) matching](#sec-28)
- [20.6 `pd.merge_ordered()` — ordered outer merge with filling](#sec-29)
- [20.7 Combining time-series data & 20.8 concatenating many files/DataFrames](#sec-30)
- [21. Common Mistakes](#sec-31)

> ✍️ Practice problems with solutions: [Topic_10_Practice_Solutions.ipynb](Topic_10_Practice_Solutions.ipynb)  ·  🗂️ [All topics](../Topic_00_All_Topics_Index.ipynb)

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.width', 130)
pd.set_option('display.max_columns', 30)
print('pandas', pd.__version__)

pandas 3.0.3


---
<a id="sec-1"></a>
# 1. Why Do We Combine DataFrames?

### Real data lives in several tables
Databases split information into separate tables so each fact is stored **once** (this is called **normalization**):

| Table | One row = | Example columns |
|---|---|---|
| **Customers** | one customer | Customer_ID, Name, City, Age |
| **Orders** | one order | Order_ID, Customer_ID, Product_ID, Quantity, Date |
| **Products** | one product | Product_ID, Product, Category, Price |
| **Employees** | one employee | Emp_ID, Name, Dept_ID |
| **Sales** | one sale | Sale_ID, Emp_ID, Amount |
| **Monthly files** | one month's data | same columns in `jan.csv`, `feb.csv`, `mar.csv` |

### Why not one giant table?
- If a customer moves city, you update **one** row in Customers, not 500 order rows.
- Less storage and fewer inconsistencies (no "Lahore" in one order and "Karachi" in another for the same customer).

### But for analysis we need them together
"Revenue per **city**" needs quantities (Orders) × prices (Products) × city (Customers) → we must **combine** the tables.

```text
Customers ──Customer_ID──▶ Orders ◀──Product_ID── Products
      (merge on keys)               (merge on keys)

jan.csv
feb.csv   ──stack──▶  all months   (concat)
mar.csv
```

---
<a id="sec-2"></a>
# 2. `pd.concat()`

### What
Glues DataFrames together **along an axis** — no matching on keys, just stacking (rows) or placing side by side (columns, aligned by index).

### Syntax
```python
pd.concat(
    [df1, df2, ...],        # a LIST of DataFrames
    axis=0,                 # 0 = stack rows (default) · 1 = side by side (columns)
    ignore_index=False,     # True → new index 0..n-1
    keys=None,              # labels for each piece → MultiIndex (remember where rows came from)
    join='outer',           # 'outer' = keep all columns · 'inner' = only shared columns
)
```

| Parameter | Effect |
|---|---|
| `axis=0` | Rows of df2 go **below** df1 |
| `axis=1` | Columns of df2 go **to the right** of df1 (rows matched by **index**) |
| `ignore_index=True` | Throw away old indexes, create 0, 1, 2 … (avoids duplicate index labels) |
| `keys=['a', 'b']` | Add an outer index level showing the source of each row |
| `join='inner'` | Keep only columns (axis=0) / index labels (axis=1) present in **all** pieces |

### Why / When
Same kind of data split into pieces: monthly files, data from several branches, results of a loop, adding computed columns that share the same index.

### When not
Matching rows by an ID column (customer ↔ order) → that's **merge**.

In [2]:
df1 = pd.DataFrame({'Name': ['Ali', 'Sara'], 'Score': [85, 92]})
df2 = pd.DataFrame({'Name': ['Omar', 'Hina'], 'Score': [78, 88]})

print('pd.concat([df1, df2]) — note the repeated index 0, 1, 0, 1:')
print(pd.concat([df1, df2]), '\n')
print('ignore_index=True:')
print(pd.concat([df1, df2], ignore_index=True), '\n')
print("keys=['Class A', 'Class B']:")
print(pd.concat([df1, df2], keys=['Class A', 'Class B']))

pd.concat([df1, df2]) — note the repeated index 0, 1, 0, 1:
   Name  Score
0   Ali     85
1  Sara     92
0  Omar     78
1  Hina     88 

ignore_index=True:
   Name  Score
0   Ali     85
1  Sara     92
2  Omar     78
3  Hina     88 

keys=['Class A', 'Class B']:
           Name  Score
Class A 0   Ali     85
        1  Sara     92
Class B 0  Omar     78
        1  Hina     88


### Expected output & explanation
- Plain `concat` keeps the original indexes → labels `0, 1, 0, 1` (duplicates! `.loc[0]` would return 2 rows).
- `ignore_index=True` gives a clean `0, 1, 2, 3`.
- `keys=` adds an outer level (`Class A`/`Class B`) so you still know where each row came from.

### Common mistakes
Passing DataFrames without a list (`pd.concat(df1, df2)` → error) · forgetting `ignore_index=True` · calling concat inside a loop (slow — collect pieces in a list and concat **once**, Section 20).

---
<a id="sec-3"></a>
# 3. Row-wise Concatenation (monthly datasets)

Monthly exports usually have **identical columns**. Stack them into one table and remember the month.

In [3]:
jan = pd.DataFrame({'Order_ID': [1, 2, 3], 'Product': ['Pen', 'Book', 'Bag'], 'Amount': [50, 400, 1200]})
feb = pd.DataFrame({'Order_ID': [4, 5], 'Product': ['Pen', 'Lamp'], 'Amount': [60, 2200]})
mar = pd.DataFrame({'Order_ID': [6, 7, 8], 'Product': ['Book', 'Bag', 'Pen'], 'Amount': [380, 1150, 55]})

q1 = pd.concat([jan, feb, mar], keys=['Jan', 'Feb', 'Mar'], names=['Month', 'Row']).reset_index(level='Month').reset_index(drop=True)
print(q1, '\n')
print('Total per month:'); print(q1.groupby('Month', sort=False)['Amount'].sum())

  Month  Order_ID Product  Amount
0   Jan         1     Pen      50
1   Jan         2    Book     400
2   Jan         3     Bag    1200
3   Feb         4     Pen      60
4   Feb         5    Lamp    2200
5   Mar         6    Book     380
6   Mar         7     Bag    1150
7   Mar         8     Pen      55 

Total per month:
Month
Jan    1650
Feb    2260
Mar    1585
Name: Amount, dtype: int64


### Explanation
`keys` + `names` created a `Month` index level; `reset_index(level='Month')` turned it into a normal column, and `reset_index(drop=True)` gave a clean 0..7 index. An alternative is to add the column before concatenating: `jan.assign(Month='Jan')`.

### Common mistakes
Losing track of which file a row came from (use `keys` or add a column) · columns with slightly different names (`Amount` vs `amount`) → they become **separate** columns full of NaN (Section 5).

---
<a id="sec-4"></a>
# 4. Column-wise Concatenation — `axis=1`

### What
Places DataFrames **side by side**. Rows are matched by their **index labels**, not by position!

### When
Adding columns that were computed from the same rows (same index), e.g. features created in separate steps.

### When not
Combining tables that share an ID column but have different row orders/indexes → use **merge**.

In [4]:
info = pd.DataFrame({'Name': ['Ali', 'Sara', 'Omar']}, index=[0, 1, 2])
scores = pd.DataFrame({'Score': [85, 92, 78]}, index=[0, 1, 2])
print('Same index → rows line up:')
print(pd.concat([info, scores], axis=1), '\n')

scores_shuffled = pd.DataFrame({'Score': [78, 85, 92]}, index=[2, 0, 1])     # same data, different order
print('Different order but same labels → still aligned correctly by index:')
print(pd.concat([info, scores_shuffled], axis=1), '\n')

scores_new_index = pd.DataFrame({'Score': [85, 92, 78]}, index=[10, 11, 12])  # e.g. after filtering/sorting elsewhere
print('Different index labels → NO alignment → NaNs and 6 rows:')
print(pd.concat([info, scores_new_index], axis=1), '\n')
print('Fix: reset both indexes if the rows really are in the same order:')
print(pd.concat([info.reset_index(drop=True), scores_new_index.reset_index(drop=True)], axis=1))

Same index → rows line up:
   Name  Score
0   Ali     85
1  Sara     92
2  Omar     78 

Different order but same labels → still aligned correctly by index:
   Name  Score
0   Ali     85
1  Sara     92
2  Omar     78 

Different index labels → NO alignment → NaNs and 6 rows:
    Name  Score
0    Ali    NaN
1   Sara    NaN
2   Omar    NaN
10   NaN   85.0
11   NaN   92.0
12   NaN   78.0 

Fix: reset both indexes if the rows really are in the same order:
   Name  Score
0   Ali     85
1  Sara     92
2  Omar     78


### Explanation
`axis=1` performs an **outer join on the index**. When the labels don't match, pandas cannot guess which rows belong together, so it keeps all labels and fills gaps with NaN. `join='inner'` would keep only labels present in both.

### Common mistakes
Assuming `axis=1` matches by position · forgetting that filtering/sorting changes the index before concatenating.

---
<a id="sec-5"></a>
# 5. `concat()` with Different Columns

When pieces have **different columns**:
- `join='outer'` (default): keep **all** columns; missing values become **NaN**.
- `join='inner'`: keep only the columns present in **every** piece.

In [5]:
branch_a = pd.DataFrame({'Order_ID': [1, 2], 'Amount': [500, 800], 'Coupon': ['SAVE10', None]})
branch_b = pd.DataFrame({'Order_ID': [3, 4], 'Amount': [300, 900], 'Delivery_Fee': [150, 0]})

print("join='outer' (default):")
print(pd.concat([branch_a, branch_b], ignore_index=True), '\n')
print("join='inner':")
print(pd.concat([branch_a, branch_b], ignore_index=True, join='inner'))

join='outer' (default):
   Order_ID  Amount  Coupon  Delivery_Fee
0         1     500  SAVE10           NaN
1         2     800     NaN           NaN
2         3     300     NaN         150.0
3         4     900     NaN           0.0 

join='inner':
   Order_ID  Amount
0         1     500
1         2     800
2         3     300
3         4     900


### Explanation
- **Outer:** `Coupon` is NaN for branch B's rows and `Delivery_Fee` is NaN for branch A's rows — because those columns didn't exist there.
- **Inner:** only `Order_ID` and `Amount` (shared by both) survive.

### Common mistakes
A typo or different capitalisation in one file silently creates an extra NaN-filled column → standardise column names **before** concatenating (`df.columns.str.strip().str.lower()`).

---
<a id="sec-6"></a>
# 6. `pd.merge()` — joining tables on a key

### What
Combines two DataFrames by **matching values in one or more key columns** — exactly like SQL `JOIN`.

### Syntax
```python
pd.merge(left, right,
         on='Customer_ID',          # key column with the same name in both
         how='inner',               # 'inner' (default), 'left', 'right', 'outer', 'cross'
         left_on=None, right_on=None,   # when the key names differ
         suffixes=('_x', '_y'),     # for overlapping non-key column names
         validate=None,             # check the relationship ('one_to_one', ...)
         indicator=False)           # add a _merge column showing where each row came from
left.merge(right, on='Customer_ID', how='left')   # same thing, method style
```

### Why / When
Related information stored in different tables (customers ↔ orders ↔ products).

### When not
Stacking tables with the same columns → `concat`. Matching on the **index** → `join` (or `merge(left_index=True, right_index=True)`).

In [6]:
customers = pd.DataFrame({'Customer_ID': [1, 2, 3, 4], 'Name': ['Ali', 'Sara', 'Omar', 'Hina'],
                          'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad']})
orders = pd.DataFrame({'Order_ID': [101, 102, 103, 104, 105], 'Customer_ID': [1, 2, 1, 5, 3],
                       'Amount': [500, 1200, 300, 900, 750]})
print('customers:'); print(customers, '\n')
print('orders:'); print(orders, '\n')
print("pd.merge(orders, customers, on='Customer_ID'):")
print(pd.merge(orders, customers, on='Customer_ID'))

customers:
   Customer_ID  Name       City
0            1   Ali     Lahore
1            2  Sara    Karachi
2            3  Omar     Lahore
3            4  Hina  Islamabad 

orders:
   Order_ID  Customer_ID  Amount
0       101            1     500
1       102            2    1200
2       103            1     300
3       104            5     900
4       105            3     750 

pd.merge(orders, customers, on='Customer_ID'):
   Order_ID  Customer_ID  Amount  Name     City
0       101            1     500   Ali   Lahore
1       102            2    1200  Sara  Karachi
2       103            1     300   Ali   Lahore
3       105            3     750  Omar   Lahore


### Expected output & explanation
Each order gets the name and city of its customer. Ali (ID 1) placed two orders → his details appear twice. Order 104 (customer 5, who doesn't exist in `customers`) and Hina (ID 4, no orders) are **missing** from the result — because the default `how='inner'` keeps only matches. Section 7 shows the other options.

---
<a id="sec-7"></a>
# 7. Types of Merge

We use the same two small tables for every join type:
- **customers**: IDs 1, 2, 3, 4 (Hina = 4 has **no orders**)
- **orders**: customer IDs 1, 2, 1, **5**, 3 (customer 5 **doesn't exist** in customers)

<a id="sec-8"></a>
## 7.1 Inner join — `how='inner'`
**Keeps:** only keys found in **both** tables.
**Use when:** you only care about complete matches (e.g. orders with a known customer).

In [7]:
inner = pd.merge(customers, orders, on='Customer_ID', how='inner')
print(inner)
print('\nRows:', len(inner), '| Hina (no orders) dropped, order 104 (unknown customer 5) dropped')

   Customer_ID  Name     City  Order_ID  Amount
0            1   Ali   Lahore       101     500
1            1   Ali   Lahore       103     300
2            2  Sara  Karachi       102    1200
3            3  Omar   Lahore       105     750

Rows: 4 | Hina (no orders) dropped, order 104 (unknown customer 5) dropped


<a id="sec-9"></a>
## 7.2 Left join — `how='left'`
**Keeps:** **all rows of the left** table; right-side columns are NaN where there is no match.
**Use when:** the left table is your "main" list and you want to **enrich** it (e.g. all customers + their orders, including customers who never ordered). The most common join in analysis.

In [8]:
left = pd.merge(customers, orders, on='Customer_ID', how='left')
print(left)
print('\nRows:', len(left), '| Hina kept with NaN order columns; order 104 dropped (its customer is not in the left table)')

   Customer_ID  Name       City  Order_ID  Amount
0            1   Ali     Lahore     101.0   500.0
1            1   Ali     Lahore     103.0   300.0
2            2  Sara    Karachi     102.0  1200.0
3            3  Omar     Lahore     105.0   750.0
4            4  Hina  Islamabad       NaN     NaN

Rows: 5 | Hina kept with NaN order columns; order 104 dropped (its customer is not in the left table)


<a id="sec-10"></a>
## 7.3 Right join — `how='right'`
**Keeps:** **all rows of the right** table.
**Use when:** the right table is the main one. (Equivalent to a left join with the tables swapped — most people swap and use `left` for readability.)

In [9]:
right = pd.merge(customers, orders, on='Customer_ID', how='right')
print(right)
print('\nRows:', len(right), '| every order kept; order 104 has NaN Name/City (unknown customer 5); Hina dropped')

   Customer_ID  Name     City  Order_ID  Amount
0            1   Ali   Lahore       101     500
1            2  Sara  Karachi       102    1200
2            1   Ali   Lahore       103     300
3            5   NaN      NaN       104     900
4            3  Omar   Lahore       105     750

Rows: 5 | every order kept; order 104 has NaN Name/City (unknown customer 5); Hina dropped


<a id="sec-11"></a>
## 7.4 Outer join — `how='outer'`
**Keeps:** **all keys from both** tables; NaN wherever a side has no match.
**Use when:** you need the complete picture, e.g. **reconciling** two systems and finding what's missing on either side.

In [10]:
outer = pd.merge(customers, orders, on='Customer_ID', how='outer')
print(outer)
print('\nRows:', len(outer), '| Hina (no orders) AND order 104 (unknown customer) are both kept')

   Customer_ID  Name       City  Order_ID  Amount
0            1   Ali     Lahore     101.0   500.0
1            1   Ali     Lahore     103.0   300.0
2            2  Sara    Karachi     102.0  1200.0
3            3  Omar     Lahore     105.0   750.0
4            4  Hina  Islamabad       NaN     NaN
5            5   NaN        NaN     104.0   900.0

Rows: 6 | Hina (no orders) AND order 104 (unknown customer) are both kept


### Common mistakes
- Using `inner` by default and silently **losing rows** (always compare row counts before/after).
- Using `left` with the tables in the wrong order.
- Integer columns become **float** after a left/outer join when NaNs appear (e.g. `Order_ID` 101.0) — convert back with `astype('Int64')` if needed.

---
<a id="sec-12"></a>
# 8. Visual Explanation of Joins

```text
          customers (left)            orders (right)
          Customer_ID                 Customer_ID
              1  ◀───── match ─────▶   1, 1
              2  ◀───── match ─────▶   2
              3  ◀───── match ─────▶   3
              4   (no orders)
                                       5   (unknown customer)

  INNER  →  1, 1, 2, 3                 only the matches
  LEFT   →  1, 1, 2, 3, 4(NaN)         all customers
  RIGHT  →  1, 1, 2, 3, 5(NaN)         all orders
  OUTER  →  1, 1, 2, 3, 4(NaN), 5(NaN) everything
```

Venn-style picture (L = left keys, R = right keys):
```text
   INNER            LEFT             RIGHT            OUTER
  ( L (█) R )     (█L█(█) R )      ( L (█)█R█)      (█L█(█)█R█)
   only overlap    all of L          all of R         everything
```

In [11]:
summary = pd.DataFrame({
    how: [len(pd.merge(customers, orders, on='Customer_ID', how=how)),
          sorted(pd.merge(customers, orders, on='Customer_ID', how=how)['Customer_ID'].unique().tolist())]
    for how in ['inner', 'left', 'right', 'outer']
}, index=['Rows', 'Customer_IDs present']).T
summary

,Rows,Customer_IDs present
inner,4,"[1, 2, 3]"
left,5,"[1, 2, 3, 4]"
right,5,"[1, 2, 3, 5]"
outer,6,"[1, 2, 3, 4, 5]"


---
<a id="sec-13"></a>
# 9. Merge on Different Column Names — `left_on` / `right_on`

### When
The same key has different names in each table (`customer_id` vs `id`) — very common when tables come from different systems.

```python
pd.merge(orders, customers, left_on='customer_id', right_on='id', how='left')
```
Both key columns are kept in the result; drop the redundant one afterwards.

In [12]:
orders_sys = pd.DataFrame({'order_no': [1, 2, 3], 'customer_id': [10, 11, 10], 'total': [250, 900, 400]})
crm = pd.DataFrame({'id': [10, 11, 12], 'full_name': ['Ali Khan', 'Sara Ahmed', 'Omar Farooq']})
merged9 = pd.merge(orders_sys, crm, left_on='customer_id', right_on='id', how='left').drop(columns='id')
merged9

,order_no,customer_id,total,full_name
0,1,10,250,Ali Khan
1,2,11,900,Sara Ahmed
2,3,10,400,Ali Khan


### Common mistakes
Forgetting that both columns remain (duplicate information) · swapping `left_on`/`right_on` so they refer to the wrong table.

---
<a id="sec-14"></a>
# 10. Multiple Keys (composite keys)

### What
Sometimes **one column is not enough** to identify a row. A **composite key** combines several columns, e.g. (`Customer_ID`, `Product_ID`) — one customer can have many products and one product many customers, but the **pair** identifies one row.

```python
pd.merge(df1, df2, on=['Customer_ID', 'Product_ID'])
```

In [13]:
purchases = pd.DataFrame({'Customer_ID': [1, 1, 2, 2], 'Product_ID': ['P1', 'P2', 'P1', 'P3'], 'Qty': [2, 1, 5, 1]})
reviews = pd.DataFrame({'Customer_ID': [1, 2, 2], 'Product_ID': ['P1', 'P1', 'P2'], 'Stars': [5, 3, 4]})

print('Composite key (Customer_ID, Product_ID):')
print(pd.merge(purchases, reviews, on=['Customer_ID', 'Product_ID'], how='left'), '\n')
print('❌ Only Customer_ID — wrong pairs and extra rows:')
print(pd.merge(purchases, reviews, on='Customer_ID', how='left'))

Composite key (Customer_ID, Product_ID):


   Customer_ID Product_ID  Qty  Stars
0            1         P1    2    5.0
1            1         P2    1    NaN
2            2         P1    5    3.0
3            2         P3    1    NaN 

❌ Only Customer_ID — wrong pairs and extra rows:
   Customer_ID Product_ID_x  Qty Product_ID_y  Stars
0            1           P1    2           P1      5
1            1           P2    1           P1      5
2            2           P1    5           P1      3
3            2           P1    5           P2      4
4            2           P3    1           P1      3
5            2           P3    1           P2      4


### Explanation
With the composite key, each purchase gets **its own** review (or NaN). Merging on `Customer_ID` alone pairs every purchase of a customer with every review of that customer → wrong combinations and more rows.

---
<a id="sec-15"></a>
# 11. Merge with Suffixes

### What
If both tables have a **non-key column with the same name** (e.g. `City` in customers and `City` in orders = delivery city), pandas renames them with suffixes. The default is `_x`/`_y` — unclear! Set your own:

```python
pd.merge(customers, orders, on='Customer_ID', suffixes=('_customer', '_order'))
```

In [14]:
cust11 = pd.DataFrame({'Customer_ID': [1, 2], 'City': ['Lahore', 'Karachi'], 'Date': ['2024-01-10', '2024-03-05']})
ord11 = pd.DataFrame({'Customer_ID': [1, 1, 2], 'City': ['Lahore', 'Islamabad', 'Karachi'], 'Date': ['2025-02-01', '2025-02-15', '2025-03-01']})
print('Default suffixes:'); print(pd.merge(cust11, ord11, on='Customer_ID'), '\n')
m11 = pd.merge(cust11, ord11, on='Customer_ID', suffixes=('_customer', '_order'))
print('Custom suffixes:'); print(m11, '\n')
print('Orders delivered outside the home city:')
print(m11[m11['City_customer'] != m11['City_order']])

Default suffixes:
   Customer_ID   City_x      Date_x     City_y      Date_y
0            1   Lahore  2024-01-10     Lahore  2025-02-01
1            1   Lahore  2024-01-10  Islamabad  2025-02-15
2            2  Karachi  2024-03-05    Karachi  2025-03-01 

Custom suffixes:
   Customer_ID City_customer Date_customer City_order  Date_order
0            1        Lahore    2024-01-10     Lahore  2025-02-01
1            1        Lahore    2024-01-10  Islamabad  2025-02-15
2            2       Karachi    2024-03-05    Karachi  2025-03-01 

Orders delivered outside the home city:
   Customer_ID City_customer Date_customer City_order  Date_order
1            1        Lahore    2024-01-10  Islamabad  2025-02-15


### Common mistakes
Leaving `_x`/`_y` in final reports · not noticing that a column you expected (`City`) no longer exists after the merge (it's now `City_x`).

---
<a id="sec-16"></a>
# 12. Relationship Types: One-to-One, One-to-Many, Many-to-One, Many-to-Many

| Relationship | Meaning | Example | Result rows |
|---|---|---|---|
| **One-to-one (1:1)** | Each key appears **once** on both sides | Employee ↔ Employee_Details | ≈ same as the inputs |
| **One-to-many (1:m)** | Key unique on the **left**, repeated on the right | Customer (1) → Orders (many) | = number of right rows (matched) |
| **Many-to-one (m:1)** | Key repeated on the left, unique on the right | Orders (many) → Product (1) — the most common "lookup" merge | = number of left rows |
| **Many-to-many (m:m)** | Key repeated on **both** sides | Students ↔ Courses via a shared "Class" code | **Multiplies**: each left copy × each right copy |

⚠️ In a many-to-many merge, a key appearing 3 times on the left and 4 times on the right produces **3 × 4 = 12 rows** for that key. Usually this is a **bug** (a key you thought was unique isn't).

In [15]:
emp = pd.DataFrame({'Emp_ID': [1, 2, 3], 'Name': ['Ali', 'Sara', 'Omar']})
emp_details = pd.DataFrame({'Emp_ID': [1, 2, 3], 'Salary': [90000, 85000, 70000]})
products = pd.DataFrame({'Product_ID': ['P1', 'P2'], 'Price': [500, 1200]})
order_lines = pd.DataFrame({'Order_ID': [1, 2, 3, 4], 'Product_ID': ['P1', 'P1', 'P2', 'P1']})
teachers = pd.DataFrame({'Class': ['A', 'A', 'B'], 'Teacher': ['Mr. Khan', 'Ms. Noor', 'Mr. Ali']})
pupils = pd.DataFrame({'Class': ['A', 'A', 'A', 'B'], 'Pupil': ['Hina', 'Bilal', 'Zara', 'Usman']})

print('1:1 →', len(pd.merge(emp, emp_details, on='Emp_ID')), 'rows (3 employees)')
print('1:m →', len(pd.merge(customers, orders, on='Customer_ID')), 'rows (one per matched order)')
print('m:1 →', len(pd.merge(order_lines, products, on='Product_ID')), 'rows (one per order line)')
mm = pd.merge(teachers, pupils, on='Class')
print('m:m →', len(mm), 'rows = class A: 2 teachers × 3 pupils = 6, class B: 1 × 1 = 1')
mm

1:1 → 3 rows (3 employees)
1:m → 4 rows (one per matched order)
m:1 → 4 rows (one per order line)
m:m → 7 rows = class A: 2 teachers × 3 pupils = 6, class B: 1 × 1 = 1


,Class,Teacher,Pupil
0,A,Mr. Khan,Hina
1,A,Mr. Khan,Bilal
2,A,Mr. Khan,Zara
3,A,Ms. Noor,Hina
4,A,Ms. Noor,Bilal
5,A,Ms. Noor,Zara
6,B,Mr. Ali,Usman


---
<a id="sec-17"></a>
# 13. Validate the Merge — `validate=`

### What
Tells pandas the relationship you **expect**; it raises a `MergeError` if the data disagrees.

| Value | Checks |
|---|---|
| `'one_to_one'` / `'1:1'` | Keys unique on **both** sides |
| `'one_to_many'` / `'1:m'` | Keys unique on the **left** |
| `'many_to_one'` / `'m:1'` | Keys unique on the **right** (typical lookup) |
| `'many_to_many'` / `'m:m'` | No check (documents intent) |

### Why it helps
A product table that accidentally contains `P1` twice would silently **duplicate every order line** of P1 and inflate revenue. `validate='many_to_one'` stops the merge immediately and tells you why.

In [16]:
print('✔ OK:', len(pd.merge(order_lines, products, on='Product_ID', validate='many_to_one')), 'rows')

products_bad = pd.concat([products, pd.DataFrame({'Product_ID': ['P1'], 'Price': [550]})], ignore_index=True)   # P1 twice!
print('Without validation → silently', len(pd.merge(order_lines, products_bad, on='Product_ID')), 'rows instead of 4')
try:
    pd.merge(order_lines, products_bad, on='Product_ID', validate='many_to_one')
except pd.errors.MergeError as e:
    print('With validate="many_to_one" → MergeError:', str(e).split('\n')[0])

✔ OK: 4 rows
Without validation → silently 7 rows instead of 4
With validate="many_to_one" → MergeError: Merge keys are not unique in right dataset; not a many-to-one merge


### Common mistakes
Never validating lookup merges · choosing the wrong direction (`one_to_many` vs `many_to_one` depends on which table is **left**).

---
<a id="sec-18"></a>
# 14. Merge Indicator — `indicator=True`

Adds a `_merge` column telling where each row came from:

| `_merge` value | Meaning |
|---|---|
| `both` | Key found in both tables |
| `left_only` | Only in the left table (e.g. customers without orders) |
| `right_only` | Only in the right table (e.g. orders with an unknown customer → data-quality problem!) |

Use it with `how='outer'` to **reconcile** two tables.

In [17]:
check = pd.merge(customers, orders, on='Customer_ID', how='outer', indicator=True)
print(check[['Customer_ID', 'Name', 'Order_ID', '_merge']], '\n')
print(check['_merge'].value_counts(), '\n')
print('Customers with no orders :', check.loc[check['_merge'] == 'left_only', 'Name'].tolist())
print('Orders with unknown customer:', check.loc[check['_merge'] == 'right_only', 'Order_ID'].astype(int).tolist())

# Anti-join: rows of the left table that have NO match in the right table
no_orders = (customers.merge(orders[['Customer_ID']].drop_duplicates(), on='Customer_ID', how='left', indicator=True)
             .query('_merge == "left_only"').drop(columns='_merge'))
print('\nAnti-join result:'); print(no_orders)

   Customer_ID  Name  Order_ID      _merge
0            1   Ali     101.0        both
1            1   Ali     103.0        both
2            2  Sara     102.0        both
3            3  Omar     105.0        both
4            4  Hina       NaN   left_only
5            5   NaN     104.0  right_only 

_merge
both          4
left_only     1
right_only    1
Name: count, dtype: int64 

Customers with no orders : ['Hina']
Orders with unknown customer: [104]

Anti-join result:
   Customer_ID  Name       City
3            4  Hina  Islamabad


---
<a id="sec-19"></a>
# 15. `df.join()`

### What
A convenience method that combines DataFrames **using the index** (row labels). By default it's a **left** join on the index.

```python
left.join(right)                               # left index ↔ right index, how='left'
left.join(right, how='inner' / 'outer' / 'right')
left.join(right, on='Customer_ID')             # left COLUMN ↔ right INDEX
left.join(right, lsuffix='_l', rsuffix='_r')   # needed if column names overlap
left.join([df2, df3])                          # several tables at once (all on the index)
```

### Why / When
Tables that are already **indexed by their key** (e.g. results of `groupby`, `set_index('Customer_ID')`, time-indexed data).

### When not
Joining on ordinary columns on both sides → `merge` is clearer.

In [18]:
cust_idx = customers.set_index('Customer_ID')                                    # index = Customer_ID
totals = orders.groupby('Customer_ID')['Amount'].agg(Total_Spent='sum', Orders='count')   # index = Customer_ID

print("join (default how='left'):"); print(cust_idx.join(totals), '\n')
print("join how='inner':"); print(cust_idx.join(totals, how='inner'), '\n')
print("join how='outer' (customer 5 appears with NaN name):"); print(cust_idx.join(totals, how='outer'), '\n')

print("orders.join(cust_idx, on='Customer_ID') — column on the left, index on the right:")
print(orders.join(cust_idx, on='Customer_ID'))

join (default how='left'):
             Name       City  Total_Spent  Orders
Customer_ID                                      
1             Ali     Lahore        800.0     2.0
2            Sara    Karachi       1200.0     1.0
3            Omar     Lahore        750.0     1.0
4            Hina  Islamabad          NaN     NaN 

join how='inner':
             Name     City  Total_Spent  Orders
Customer_ID                                    
1             Ali   Lahore          800       2
2            Sara  Karachi         1200       1
3            Omar   Lahore          750       1 

join how='outer' (customer 5 appears with NaN name):
             Name       City  Total_Spent  Orders
Customer_ID                                      
1             Ali     Lahore        800.0     2.0
2            Sara    Karachi       1200.0     1.0
3            Omar     Lahore        750.0     1.0
4            Hina  Islamabad          NaN     NaN
5             NaN        NaN        900.0     1.0 

orders

   Order_ID  Customer_ID  Amount  Name     City
0       101            1     500   Ali   Lahore
1       102            2    1200  Sara  Karachi
2       103            1     300   Ali   Lahore
3       104            5     900   NaN      NaN
4       105            3     750  Omar   Lahore


### Common mistakes
Forgetting that `join` uses the **index** of the right table (join on a column that isn't set as the index → wrong or no matches) · overlapping column names without `lsuffix`/`rsuffix` → `ValueError`.

---
<a id="sec-20"></a>
# 16. `merge` vs `join` vs `concat`

| Method | Main purpose | Uses key columns? | Uses index? | Default | Common use |
|---|---|---|---|---|---|
| `pd.concat` | **Stack/glue** DataFrames along an axis | ❌ No | ✅ aligns on index (axis=1) / columns (axis=0) | outer, axis=0 | Monthly files, adding rows, side-by-side columns with the same index |
| `pd.merge` / `df.merge` | **Match rows by key values** (SQL-style) | ✅ `on`, `left_on`, `right_on` | Optional (`left_index`, `right_index`) | inner | Customers ↔ orders ↔ products |
| `df.join` | Match rows **by index** (shortcut for merge) | Only on the left (`on=`) | ✅ right side always index | left | Adding groupby results or indexed lookup tables |

**In one sentence each:**
- **concat** = "put these tables **together**" (no matching).
- **merge** = "**match** these tables using these columns".
- **join** = "match using the **row labels**".

### Same data, three methods

In [19]:
scores = pd.DataFrame({'Student': ['Ali', 'Sara', 'Omar'], 'Math': [85, 92, 78]})
extra = pd.DataFrame({'Student': ['Omar', 'Ali', 'Hina'], 'English': [70, 88, 95]})     # different ORDER, one new student

print('concat axis=0 (stack rows — no matching!):')
print(pd.concat([scores, extra], ignore_index=True), '\n')
print('concat axis=1 (side by side by POSITION/index — WRONG pairing: Ali gets Omar\'s English):')
print(pd.concat([scores, extra], axis=1), '\n')
print("merge on 'Student' (correct pairing by name):")
print(pd.merge(scores, extra, on='Student', how='outer'), '\n')
print('join on index after set_index (same as merge):')
print(scores.set_index('Student').join(extra.set_index('Student'), how='outer'))

concat axis=0 (stack rows — no matching!):
  Student  Math  English
0     Ali  85.0      NaN
1    Sara  92.0      NaN
2    Omar  78.0      NaN
3    Omar   NaN     70.0
4     Ali   NaN     88.0
5    Hina   NaN     95.0 

concat axis=1 (side by side by POSITION/index — WRONG pairing: Ali gets Omar's English):
  Student  Math Student  English
0     Ali    85    Omar       70
1    Sara    92     Ali       88
2    Omar    78    Hina       95 

merge on 'Student' (correct pairing by name):
  Student  Math  English
0     Ali  85.0     88.0
1    Hina   NaN     95.0
2    Omar  78.0     70.0
3    Sara  92.0      NaN 

join on index after set_index (same as merge):
         Math  English
Student               
Ali      85.0     88.0
Hina      NaN     95.0
Omar     78.0     70.0
Sara     92.0      NaN


### Explanation
Only `merge` (or `join` after setting the key as the index) pairs **Ali's Math with Ali's English**. `concat(axis=1)` blindly pairs row 0 with row 0 — a silent error because the second table is in a different order.

---
<a id="sec-21"></a>
# 17. Handling Duplicate Keys

### What happens
If a key that should be unique appears several times, every copy matches every copy on the other side → **row multiplication**, double-counted revenue, inflated averages.

### How to detect
```python
df['key'].duplicated().sum()          # how many repeated keys
df[df['key'].duplicated(keep=False)]  # show all copies
df['key'].value_counts().head()       # keys with count > 1
df['key'].is_unique                   # True/False
```

In [20]:
prices = pd.DataFrame({'Product_ID': ['P1', 'P2', 'P3', 'P2'], 'Price': [500, 1200, 300, 1250]})   # P2 twice (price update not cleaned)
sales = pd.DataFrame({'Sale_ID': range(1, 7), 'Product_ID': ['P1', 'P2', 'P2', 'P3', 'P2', 'P1'], 'Qty': [1, 2, 1, 3, 1, 2]})

print('Is Product_ID unique in prices?', prices['Product_ID'].is_unique)
print('value_counts:'); print(prices['Product_ID'].value_counts().head(3))
print('Duplicated rows:'); print(prices[prices['Product_ID'].duplicated(keep=False)], '\n')

bad = sales.merge(prices, on='Product_ID')
print(f'Sales rows: {len(sales)} → after merge: {len(bad)}  ← row multiplication!')
print('Revenue (wrong):', (bad['Qty'] * bad['Price']).sum())

prices_clean = prices.drop_duplicates(subset='Product_ID', keep='last')                  # keep the latest price
good = sales.merge(prices_clean, on='Product_ID', validate='many_to_one')
print('Revenue (correct, one price per product):', (good['Qty'] * good['Price']).sum(), '| rows:', len(good))

Is Product_ID unique in prices? False
value_counts:
Product_ID
P2    2
P1    1
P3    1
Name: count, dtype: int64
Duplicated rows:
  Product_ID  Price
1         P2   1200
3         P2   1250 

Sales rows: 6 → after merge: 9  ← row multiplication!
Revenue (wrong): 12200
Revenue (correct, one price per product): 7400 | rows: 6


### Explanation
Each of the 3 P2 sales matched **both** P2 prices → 6 rows instead of 3 and revenue that is too high. After deduplicating (and validating), row counts match again. Which duplicate to keep is a **business decision** (latest price? highest?).

---
<a id="sec-22"></a>
# 18. Preventing Bad Merges — Checklist

| Check | How | Why |
|---|---|---|
| **Key uniqueness** | `df['key'].is_unique`, `duplicated().sum()` | Avoid row multiplication |
| **Missing keys** | `df['key'].isna().sum()` | NaN keys never match (or match each other unexpectedly) |
| **Data types** | `df1['key'].dtype == df2['key'].dtype` | `1` (int) ≠ `'1'` (text) → no matches or a `ValueError` |
| **Formatting** | strip spaces, same case, same leading zeros (`'007'` vs `'7'`) | Hidden mismatches |
| **Row counts** | `len()` before vs after | Detect lost rows (inner) or multiplied rows (duplicates) |
| **Unexpected nulls** | `merged.isna().sum()` after a left join | Keys that didn't match |
| **Relationship** | `validate='many_to_one'` etc. | Fail fast when assumptions break |
| **Unmatched records** | `indicator=True` | Find left_only / right_only rows |

In [21]:
ord18 = pd.DataFrame({'Order_ID': [1, 2, 3, 4], 'Customer_ID': ['C01', 'c02 ', 'C03', None]})
cus18 = pd.DataFrame({'Customer_ID': ['C01', 'C02', 'C03', 'C04'], 'Name': ['Ali', 'Sara', 'Omar', 'Hina']})

def merge_report(left, right, key, how='left', **kw):
    '''Merge with a quick quality report.'''
    print(f'left rows={len(left)}, right rows={len(right)} | dtypes: {left[key].dtype} vs {right[key].dtype}')
    print(f'missing keys: left={left[key].isna().sum()}, right={right[key].isna().sum()} | right key unique: {right[key].is_unique}')
    out = pd.merge(left, right, on=key, how=how, indicator=True, **kw)
    print(f'result rows={len(out)} | match status: {out["_merge"].value_counts().to_dict()}')
    return out

print('BEFORE cleaning:'); r1 = merge_report(ord18, cus18, 'Customer_ID', validate='many_to_one')
ord18['Customer_ID'] = ord18['Customer_ID'].str.strip().str.upper()                    # fix formatting
print('\nAFTER cleaning:'); r2 = merge_report(ord18, cus18, 'Customer_ID', validate='many_to_one')
r2

BEFORE cleaning:
left rows=4, right rows=4 | dtypes: str vs str
missing keys: left=1, right=0 | right key unique: True
result rows=4 | match status: {'left_only': 2, 'both': 2, 'right_only': 0}

AFTER cleaning:
left rows=4, right rows=4 | dtypes: str vs str
missing keys: left=1, right=0 | right key unique: True
result rows=4 | match status: {'both': 3, 'left_only': 1, 'right_only': 0}


,Order_ID,Customer_ID,Name,_merge
0,1,C01,Ali,both
1,2,C02,Sara,both
2,3,C03,Omar,both
3,4,NaN,NaN,left_only


In [22]:
# Data-type mismatch: integers vs strings
a = pd.DataFrame({'ID': [1, 2, 3], 'x': ['a', 'b', 'c']})
b = pd.DataFrame({'ID': ['1', '2', '3'], 'y': [10, 20, 30]})
try:
    pd.merge(a, b, on='ID')
except ValueError as e:
    print('ValueError:', str(e)[:80], '...')
b['ID'] = b['ID'].astype(int)                                  # convert to the same type
print(pd.merge(a, b, on='ID'))

ValueError: You are trying to merge on int64 and str columns for key 'ID'. If you wish to pr ...
   ID  x   y
0   1  a  10
1   2  b  20
2   3  c  30


---
<a id="sec-23"></a>
# 19. Combining Real-World Tables: Customers + Orders + Products

Goal: one analytical DataFrame with every order enriched with customer and product details.

```text
orders ──(m:1 on Customer_ID)──▶ customers
   │
   └──(m:1 on Product_ID)──▶ products
```
Start from the **fact table** (orders — one row per event) and **left-join** the lookup tables, validating `many_to_one` each time.

In [23]:
customers19 = pd.DataFrame({'Customer_ID': [1, 2, 3, 4, 5], 'Name': ['Ali', 'Sara', 'Omar', 'Hina', 'Bilal'],
                            'City': ['Lahore', 'Karachi', 'Lahore', 'Islamabad', 'Karachi'], 'Age': [28, 34, 45, 23, 39]})
products19 = pd.DataFrame({'Product_ID': ['P1', 'P2', 'P3', 'P4'], 'Product': ['Laptop', 'Mouse', 'Desk', 'Lamp'],
                           'Category': ['Electronics', 'Electronics', 'Furniture', 'Furniture'], 'Price': [150000, 2500, 30000, 4500]})
orders19 = pd.DataFrame({'Order_ID': range(1001, 1009), 'Customer_ID': [1, 2, 1, 3, 5, 2, 4, 1],
                         'Product_ID': ['P1', 'P2', 'P2', 'P3', 'P4', 'P1', 'P4', 'P3'], 'Quantity': [1, 3, 2, 1, 2, 1, 4, 1]})

analytics = (orders19
             .merge(customers19, on='Customer_ID', how='left', validate='many_to_one')
             .merge(products19, on='Product_ID', how='left', validate='many_to_one'))
analytics['Revenue'] = analytics['Quantity'] * analytics['Price']
print(f'orders: {len(orders19)} rows → analytics: {len(analytics)} rows (must be equal) | nulls: {analytics.isna().sum().sum()}')
print(analytics, '\n')
print('Revenue by city:'); print(analytics.groupby('City')['Revenue'].sum().sort_values(ascending=False))
print('\nRevenue by category:'); print(analytics.groupby('Category')['Revenue'].sum())

orders: 8 rows → analytics: 8 rows (must be equal) | nulls: 0
   Order_ID  Customer_ID Product_ID  Quantity   Name       City  Age Product     Category   Price  Revenue
0      1001            1         P1         1    Ali     Lahore   28  Laptop  Electronics  150000   150000
1      1002            2         P2         3   Sara    Karachi   34   Mouse  Electronics    2500     7500
2      1003            1         P2         2    Ali     Lahore   28   Mouse  Electronics    2500     5000
3      1004            3         P3         1   Omar     Lahore   45    Desk    Furniture   30000    30000
4      1005            5         P4         2  Bilal    Karachi   39    Lamp    Furniture    4500     9000
5      1006            2         P1         1   Sara    Karachi   34  Laptop  Electronics  150000   150000
6      1007            4         P4         4   Hina  Islamabad   23    Lamp    Furniture    4500    18000
7      1008            1         P3         1    Ali     Lahore   28    Desk    Fu

---
<a id="sec-24"></a>
# 20. Advanced Combining

<a id="sec-25"></a>
## 20.1 Merge multiple DataFrames
Chain `.merge()` calls (as above), or use `functools.reduce` when you have a list of tables sharing the same key.

In [24]:
from functools import reduce
math = pd.DataFrame({'Student': ['Ali', 'Sara', 'Omar'], 'Math': [85, 92, 78]})
eng = pd.DataFrame({'Student': ['Ali', 'Sara', 'Omar'], 'English': [70, 88, 81]})
sci = pd.DataFrame({'Student': ['Ali', 'Sara', 'Omar'], 'Science': [90, 75, 84]})
reduce(lambda left, right: pd.merge(left, right, on='Student', validate='one_to_one'), [math, eng, sci])

,Student,Math,English,Science
0,Ali,85,70,90
1,Sara,92,88,75
2,Omar,78,81,84


<a id="sec-26"></a>
## 20.2 Merge after aggregation
Aggregate the "many" side **first**, then merge → no row multiplication, one summary row per customer.

In [25]:
per_customer = analytics.groupby('Customer_ID').agg(Orders=('Order_ID', 'count'), Total_Revenue=('Revenue', 'sum')).reset_index()
customer_profile = customers19.merge(per_customer, on='Customer_ID', how='left', validate='one_to_one')
customer_profile[['Orders', 'Total_Revenue']] = customer_profile[['Orders', 'Total_Revenue']].fillna(0)
customer_profile['Share_%'] = (customer_profile['Total_Revenue'] / customer_profile['Total_Revenue'].sum() * 100).round(1)
customer_profile

,Customer_ID,Name,City,Age,Orders,Total_Revenue,Share_%
0,1,Ali,Lahore,28,3,185000,46.3
1,2,Sara,Karachi,34,2,157500,39.4
2,3,Omar,Lahore,45,1,30000,7.5
3,4,Hina,Islamabad,23,1,18000,4.5
4,5,Bilal,Karachi,39,1,9000,2.3


<a id="sec-27"></a>
## 20.3 Merge with indexes, 20.4 MultiIndex joins

In [26]:
prod_idx = products19.set_index('Product_ID')
print('merge with right_index=True:')
print(pd.merge(orders19.head(3), prod_idx, left_on='Product_ID', right_index=True), '\n')

# MultiIndex: sales per (City, Category) joined with targets per (City, Category)
actual = analytics.groupby(['City', 'Category'])['Revenue'].sum()
targets = pd.DataFrame({'City': ['Lahore', 'Lahore', 'Karachi', 'Karachi', 'Islamabad'],
                        'Category': ['Electronics', 'Furniture', 'Electronics', 'Furniture', 'Furniture'],
                        'Target': [300000, 40000, 150000, 10000, 20000]}).set_index(['City', 'Category'])
print('MultiIndex join on (City, Category):')
print(targets.join(actual, how='left').assign(Achieved_pct=lambda d: (d['Revenue'] / d['Target'] * 100).round(0)))

merge with right_index=True:


   Order_ID  Customer_ID Product_ID  Quantity Product     Category   Price
0      1001            1         P1         1  Laptop  Electronics  150000
1      1002            2         P2         3   Mouse  Electronics    2500
2      1003            1         P2         2   Mouse  Electronics    2500 

MultiIndex join on (City, Category):
                       Target  Revenue  Achieved_pct
City      Category                                  
Lahore    Electronics  300000   155000          52.0
          Furniture     40000    60000         150.0
Karachi   Electronics  150000   157500         105.0
          Furniture     10000     9000          90.0
Islamabad Furniture     20000    18000          90.0


<a id="sec-28"></a>
## 20.5 `pd.merge_asof()` — nearest-key (time) matching
Matches each left row to the **most recent** (or nearest) right row by a sorted key — e.g. attach the exchange rate that was valid at the time of each transaction. Both tables must be **sorted** by the key.

<a id="sec-29"></a>
## 20.6 `pd.merge_ordered()` — ordered outer merge with filling
Merges ordered data (like dates) keeping order, with optional forward fill (`fill_method='ffill'`).

In [27]:
trades = pd.DataFrame({'Time': pd.to_datetime(['2025-03-01 10:02', '2025-03-01 10:07', '2025-03-01 10:15', '2025-03-01 10:31']),
                       'Amount_USD': [100, 250, 80, 500]})
rates = pd.DataFrame({'Time': pd.to_datetime(['2025-03-01 10:00', '2025-03-01 10:10', '2025-03-01 10:30']),
                      'PKR_per_USD': [279.5, 280.1, 280.6]})
asof = pd.merge_asof(trades.sort_values('Time'), rates.sort_values('Time'), on='Time', direction='backward')
asof['Amount_PKR'] = asof['Amount_USD'] * asof['PKR_per_USD']
print('merge_asof (latest rate at or before each trade):'); print(asof, '\n')

stock_a = pd.DataFrame({'Date': pd.to_datetime(['2025-01-01', '2025-01-03', '2025-01-05']), 'A_Price': [100, 102, 101]})
stock_b = pd.DataFrame({'Date': pd.to_datetime(['2025-01-02', '2025-01-03', '2025-01-04']), 'B_Price': [50, 51, 53]})
print('merge_ordered with forward fill:')
print(pd.merge_ordered(stock_a, stock_b, on='Date', fill_method='ffill'))

merge_asof (latest rate at or before each trade):
                 Time  Amount_USD  PKR_per_USD  Amount_PKR
0 2025-03-01 10:02:00         100        279.5     27950.0
1 2025-03-01 10:07:00         250        279.5     69875.0
2 2025-03-01 10:15:00          80        280.1     22408.0
3 2025-03-01 10:31:00         500        280.6    140300.0 

merge_ordered with forward fill:
        Date  A_Price  B_Price
0 2025-01-01      100      NaN
1 2025-01-02      100     50.0
2 2025-01-03      102     51.0
3 2025-01-04      102     53.0
4 2025-01-05      101     53.0


<a id="sec-30"></a>
## 20.7 Combining time-series data & 20.8 concatenating many files/DataFrames

In [28]:
# Time series from two sources on a shared DatetimeIndex → join (index-based)
idx = pd.date_range('2025-01-01', periods=6, freq='D')
web = pd.DataFrame({'Web_Visits': [120, 135, 128, 150, 160, 155]}, index=idx)
store = pd.DataFrame({'Store_Sales': [30, 32, 29, 40]}, index=idx[[0, 1, 3, 5]])     # some days missing
combined_ts = web.join(store, how='left')
print(combined_ts, '\n')

# Many "files": build a LIST, then concat ONCE (never concat inside the loop)
import os, tempfile
folder = tempfile.mkdtemp()
for month in ['2025-01', '2025-02', '2025-03']:
    pd.DataFrame({'Order_ID': np.arange(3) + int(month[-2:]) * 100, 'Amount': [100, 200, 300]}).to_csv(f'{folder}/sales_{month}.csv', index=False)

pieces = []
for file in sorted(os.listdir(folder)):
    part = pd.read_csv(os.path.join(folder, file))
    part['Source_File'] = file                       # remember the origin
    pieces.append(part)
all_sales = pd.concat(pieces, ignore_index=True)
print(all_sales)

            Web_Visits  Store_Sales
2025-01-01         120         30.0
2025-01-02         135         32.0
2025-01-03         128          NaN
2025-01-04         150         29.0
2025-01-05         160          NaN
2025-01-06         155         40.0 



   Order_ID  Amount        Source_File
0       100     100  sales_2025-01.csv
1       101     200  sales_2025-01.csv
2       102     300  sales_2025-01.csv
3       200     100  sales_2025-02.csv
4       201     200  sales_2025-02.csv
5       202     300  sales_2025-02.csv
6       300     100  sales_2025-03.csv
7       301     200  sales_2025-03.csv
8       302     300  sales_2025-03.csv


---
<a id="sec-31"></a>
# 21. Common Mistakes

| Mistake | Symptom | Fix |
|---|---|---|
| **Wrong join type** | Rows silently disappear (inner) or unexpected NaNs (outer) | Decide which table is the "main" one; usually `how='left'` from the fact table; compare row counts |
| **Wrong key** | Nonsense pairs, extra rows | Merge on the true identifier (or a composite key) |
| **Duplicate keys** | Row multiplication, inflated totals | `is_unique`, `duplicated()`, `validate=` |
| **Different data types** | `ValueError` or zero matches | `astype()` so both keys have the same type |
| **Missing / inconsistent keys** | Unmatched rows, NaN columns | Clean formatting (strip, upper, leading zeros); `indicator=True` |
| **Unexpected row multiplication** | `len(result) > len(fact_table)` after a lookup merge | Deduplicate the lookup table; aggregate before merging |
| **Forgetting `ignore_index`** | Duplicate index labels after concat; `.loc` returns several rows | `pd.concat(..., ignore_index=True)` |
| **Confusing `concat` with `merge`** | Rows paired by position instead of by ID | Use `merge` whenever rows must be **matched** |
| **Using the index incorrectly** | `join`/`concat(axis=1)` misaligned; NaNs | Check/`set_index` the right key; `reset_index` when needed |
| **Default suffixes `_x`/`_y`** | Confusing column names | `suffixes=('_customer', '_order')` |
| **concat in a loop** | Very slow on many files | Collect in a list, concat once |

> ✍️ **Practice time:** Practice Problems (20, increasing difficulty), ✍️ Practice Problem 1, ✍️ Practice Problem 2, ✍️ Practice Problem 3, ✍️ Practice Problem 4, ✍️ Practice Problem 5 … (+16 more) — open [Topic_10_Practice_Solutions.ipynb](Topic_10_Practice_Solutions.ipynb) to solve it and see the solution.